### ISSUE TITLE
`tox -e docs` fails locally (Fedora 35, Python 3.10)

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#363]
```
$ tox -e docs
docs develop-inst-noop: /home/plipski/git-machete
docs installed: /home/plipski/git-machete/.tox/docs/lib/python3.10/site-packages/pip/_internal/locations/_distutils.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives,  from distutils.cmd import Command as DistutilsCommand,/usr/lib64/python3.10/distutils/command/install.py:13: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead,  from distutils.sysconfig import get_config_vars,alabaster==0.7.12,Babel==2.9.1,certifi==2021.10.8,charset-normalizer==2.0.8,docutils==0.16,-e git+ssh://git@github.com/VirtusLab/git-machete.git@9005d19e35a9a3d33654626e2a7b25a3b6e8bcda#egg=git_machete,idna==3.3,imagesize==1.3.0,Jinja2==3.0.3,MarkupSafe==2.0.1,packaging==21.3,Pygments==2.10.0,pyparsing==3.0.6,pytz==2021.3,requests==2.26.0,snowballstemmer==2.2.0,Sphinx==4.1.2,sphinx-rtd-theme==0.5.2,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,urllib3==1.26.7
docs run-test-pre: PYTHONHASHSEED='2061589977'
docs run-test: commands[0] | sphinx-build -b html docs/source docs/html
Traceback (most recent call last):
  File "/home/plipski/git-machete/.tox/docs/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/home/plipski/git-machete/.tox/docs/lib/python3.10/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/plipski/git-machete/.tox/docs/lib/python3.10/site-packages/sphinx/application.py", line 32, in <module>
    from sphinx.config import Config
  File "/home/plipski/git-machete/.tox/docs/lib/python3.10/site-packages/sphinx/config.py", line 21, in <module>
    from sphinx.util import logging
  File "/home/plipski/git-machete/.tox/docs/lib/python3.10/site-packages/sphinx/util/__init__.py", line 41, in <module>
    from sphinx.util.typing import PathMatcher
  File "/home/plipski/git-machete/.tox/docs/lib/python3.10/site-packages/sphinx/util/typing.py", line 37, in <module>
    from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (/usr/lib64/python3.10/types.py)
ERROR: InvocationError for command /home/plipski/git-machete/.tox/docs/bin/sphinx-build -b html docs/source docs/html (exited with code 1)
```

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 35 (Thirty Five)
Release:	35
Codename:	ThirtyFive

$ python --version
Python 3.10.0
```

**Comment by PawelLipski** [comment]
Caused by https://github.com/sphinx-doc/sphinx/issues/9562. Fixed on `develop`.
