### ISSUE TITLE
`test_github_create_pr_missing_base_branch_on_remote` failing locally on `'NoneType' object does not support item assignment`

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#364]
```
➜ 00:24 ~/git-machete develop $ tox -epy36 -- test_github_create_pr_missing_base_branch_on_remote
py36 installed: attrs==21.2.0,autopage==0.4.0,cliff==3.10.0,cmd2==2.3.2,extras==1.0.0,fixtures==3.0.0,future==0.18.2,importlib-metadata==4.8.2,mypy==0.910,mypy-extensions==0.4.3,pbr==5.8.0,prettytable==2.4.0,pyparsing==3.0.6,pyperclip==1.8.2,python-subunit==1.4.0,PyYAML==6.0,six==1.16.0,stestr==3.2.1,stevedore==3.5.0,testtools==2.5.0,toml==0.10.2,typed-ast==1.4.3,typing_extensions==4.0.0,voluptuous==0.12.2,wcwidth==0.2.5,zipp==3.6.0
py36 run-test-pre: PYTHONHASHSEED='3553584391'
py36 run-test: commands[0] | stestr run test_github_create_pr_missing_base_branch_on_remote
/home/plipski/git-machete/.tox/py36/lib/python3.6/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
{0} git_machete.tests.functional.test_machete.MacheteTester.test_github_create_pr_missing_base_branch_on_remote [0.175366s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/lib64/python3.6/unittest/mock.py", line 1183, in patched
    return func(*args, **keywargs)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 2184, in test_github_create_pr_missing_base_branch_on_remote
    self.assert_command(['github', 'create-pr'], expected_msg, strip_indentation=False)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 376, in assert_command
    self.assertEqual(self.launch_command(*cmds), self.adapt(expected_result) if strip_indentation else expected_result)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 365, in launch_command
    cli.launch(list(args))

      File "/home/plipski/git-machete/git_machete/cli.py", line 637, in launch
    opt_onto=cli_opts.opt_onto)

      File "/home/plipski/git-machete/git_machete/client.py", line 2046, in create_github_pr
    add_assignees_to_pull_request(org, repo, pr.number, [current_user])

      File "/home/plipski/git-machete/git_machete/github.py", line 206, in add_assignees_to_pull_request
    __fire_github_api_request('POST', f'/repos/{org}/{repo}/issues/{number}/assignees', token, request_body)

      File "/home/plipski/git-machete/git_machete/github.py", line 153, in __fire_github_api_request
    http_request = urllib.request.Request(url, headers=headers, data=json_body.encode() if json_body else None, method=method.upper())

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 123, in __call__
    return self.handle_method(method)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 131, in handle_method
    return self.handle_post()

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 168, in handle_post
    return self.update_issue()

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 211, in update_issue
    return self.fill_issue_data(json.loads(self.json_data), issue)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 220, in fill_issue_data
    issue[key] = data[key]

    TypeError: 'NoneType' object does not support item assignment


==============================
Failed 1 tests - output below:
==============================

git_machete.tests.functional.test_machete.MacheteTester.test_github_create_pr_missing_base_branch_on_remote
-----------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/lib64/python3.6/unittest/mock.py", line 1183, in patched
    return func(*args, **keywargs)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 2184, in test_github_create_pr_missing_base_branch_on_remote
    self.assert_command(['github', 'create-pr'], expected_msg, strip_indentation=False)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 376, in assert_command
    self.assertEqual(self.launch_command(*cmds), self.adapt(expected_result) if strip_indentation else expected_result)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 365, in launch_command
    cli.launch(list(args))

      File "/home/plipski/git-machete/git_machete/cli.py", line 637, in launch
    opt_onto=cli_opts.opt_onto)

      File "/home/plipski/git-machete/git_machete/client.py", line 2046, in create_github_pr
    add_assignees_to_pull_request(org, repo, pr.number, [current_user])

      File "/home/plipski/git-machete/git_machete/github.py", line 206, in add_assignees_to_pull_request
    __fire_github_api_request('POST', f'/repos/{org}/{repo}/issues/{number}/assignees', token, request_body)

      File "/home/plipski/git-machete/git_machete/github.py", line 153, in __fire_github_api_request
    http_request = urllib.request.Request(url, headers=headers, data=json_body.encode() if json_body else None, method=method.upper())

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 123, in __call__
    return self.handle_method(method)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 131, in handle_method
    return self.handle_post()

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 168, in handle_post
    return self.update_issue()

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 211, in update_issue
    return self.fill_issue_data(json.loads(self.json_data), issue)

      File "/home/plipski/git-machete/git_machete/tests/functional/test_machete.py", line 220, in fill_issue_data
    issue[key] = data[key]

    TypeError: 'NoneType' object does not support item assignment



======
Totals
======
Ran: 1 tests in 0.1754 sec.
 - Passed: 0
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 1
Sum of execute time for each test: 0.1754 sec.

==============
Worker Balance
==============
 - Worker 0 (1 tests) => 0:00:00.175366
ERROR: InvocationError for command /home/plipski/git-machete/.tox/py36/bin/stestr run test_github_create_pr_missing_base_branch_on_remote (exited with code 1)
```

**Comment by PawelLipski** [comment]
Whoops... this is probably due to the fact that I've go `GITHUB_TOKEN` set up on my local machine... which gets picked up by the tests (see `git_machete.github.__get_github_token`). This needs to be taken into account in the tests... maybe by mocking `__get_github_token` to ensure predictable behavior, regardless of the local setup on dev's machine ⚙️

**Comment by PawelLipski** [comment]
More specifically: the fact that `GITHUB_TOKEN` is set up means that the test code tries to add an assignee to the pull request.

Since the assignees, as a resource shared b/w issues and PRs, live under `/issue/` and not `/pull/` API in Github... `MockGithubAPIState.get_issue` and not `get_pull` is invoked, and returns `None`.

The solution should be a rework to `MockGithubAPIState` model that takes into account the fact that certain updates to PRs are handled via `/issue/` API.
