### ISSUE TITLE
`test_github_create_pr_missing_base_branch_on_remote` consistenly fails on r.ryantm.com build system for nixpkgs

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#397]
All builds since 2021-12-06 at https://r.ryantm.com/log/updatescript/git-machete/ failed ☹️

See https://github.com/NixOS/nixpkgs/pull/145837#issuecomment-1030513026

```

2022-01-23T22:13:48 Received ExitFailure 100 when running
Raw command: /nix/store/6fr58pqy02hmgw1h7b9nqmv7vlp3v346-nix-2.3.15/bin/nix-build --option sandbox true --arg config "{ allowBroken = true; allowUnfree = true; allowAliases = false; }" --arg overlays "[ ]" -A git-machete
nix build failed.

======================================================================
FAIL: test_github_create_pr_missing_base_branch_on_remote (git_machete.tests.functional.test_machete.MacheteTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/unittest/mock.py", line 1336, in patched
    return func(*newargs, **newkeywargs)
  File "/build/source/git_machete/tests/functional/test_machete.py", line 2187, in test_github_create_pr_missing_base_branch_on_remote
    self.assert_command(['github', 'create-pr'], expected_msg, strip_indentation=False)
  File "/build/source/git_machete/tests/functional/test_machete.py", line 378, in assert_command
    self.assertEqual(self.launch_command(*cmds), self.adapt(expected_result) if strip_indentation else expected_result)
AssertionError: 'Fetc[182 chars]g`.../nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwm[604 chars]om\n' != 'Fetc[182 chars]g`... OK, see www.github.com\n'
  Fetching origin...
  Warn: Base branch for this PR (`feature/api_handling`) is not found on remote, pushing...
+ Creating a PR from `feature/api_exception_handling` to `feature/api_handling`... OK, see www.github.com
- Creating a PR from `feature/api_exception_handling` to `feature/api_handling`.../nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/subprocess.py:1052: ResourceWarning: subprocess 2749 is still running
-   _warn("subprocess %s is still running" % self.pid,
- ResourceWarning: Enable tracemalloc to get the object allocation traceback
- /build/source/git_machete/tests/functional/test_machete.py:189: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
-   'head': {'ref': "", 'repo': {'full_name': 'testing:checkout_prs', 'html_url': os.popen("mktemp -d").read().strip()}},
- ResourceWarning: Enable tracemalloc to get the object allocation traceback
-  OK, see www.github.com
```

**Comment by PawelLipski** [comment]
So, in other words, the output is polluted (and rightfully so!) with `ResourceWarning` on `subprocess ... is still running` and `unclosed file` (not sure if that's the same problem with 2 related warnings or two separate problems). This causes the test to fail on nixpkgs (but not on our CI).

EDIT: yeah, same problem... unclosed os.popen, basically

**Comment by PawelLipski** [comment]
Subtasks:
- [x] try reproducing the same failure on local machine/in the CI (maybe a matter of some extra config in tox.ini? although might as well be some race condition which only manifests itself on r.ryantm.com build system and not on devs' machines/CircleCI). Ideally, this class of errors should be captured already in our CI and not by r.ryantm.com
- [x] mention r.ryantm.com build system in CONTRIBUTING.md (as another place to be verified periodically)

**Comment by PawelLipski** [comment]
Note that #364 curiously refers to the same test, even though the failure happens under different circumstances... this might be the same bug, actually (?)

EDIT: nope, that's a total coincidence 😯
