### ISSUE TITLE
TypeError: RemoteBranchFullName needs to have `refs/remotes` prefix before branch name

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#599]
As reported by @wbar (with slight redaction to remove project-specific strings):

```
Traceback (most recent call last):
  File "/usr/local/bin/git-machete", line 20, in <module>
    cli.main()
  File "/usr/local/Cellar/git-machete/3.11.3/libexec/lib/python3.9/site-packages/git_machete/cli.py", line 829, in main
    launch(sys.argv[1:])
  File "/usr/local/Cellar/git-machete/3.11.3/libexec/lib/python3.9/site-packages/git_machete/cli.py", line 572, in launch
    machete_client.discover_tree(
  File "/usr/local/Cellar/git-machete/3.11.3/libexec/lib/python3.9/site-packages/git_machete/client.py", line 350, in discover_tree
    all_local_branches = self.__git.get_local_branches()
  File "/usr/local/Cellar/git-machete/3.11.3/libexec/lib/python3.9/site-packages/git_machete/git_operations.py", line 515, in get_local_branches
    self.__load_branches()
  File "/usr/local/Cellar/git-machete/3.11.3/libexec/lib/python3.9/site-packages/git_machete/git_operations.py", line 555, in __load_branches
    fetch_counterpart_stripped = RemoteBranchFullName.of(
  File "/usr/local/Cellar/git-machete/3.11.3/libexec/lib/python3.9/site-packages/git_machete/git_operations.py", line 94, in of
    raise TypeError(f'RemoteBranchFullName needs to have `refs/remotes` prefix before branch name. Given value: {value}.\n'
TypeError: RemoteBranchFullName needs to have `refs/remotes` prefix before branch name. Given value: refs/heads/feature/FOO-189-tests.
Consider posting an issue on https://github.com/VirtusLab/git-machete/issues/new
```

I have access to .git folder snapshot if needed (cannot share outside of the the client company, however).

**Comment by PawelLipski** [comment]
Wow, this turned out to be quite simple yet exotic case I've never thought of.... for some reason (probably developer's mistake) there is a branch `feature/FOO-249` in the repo whose remote tracking branch **is another local branch**, `feature/FOO-189-tests`:

```
$ git config -l
# ....
branch.feature/FOO-249.remote=.
branch.feature/FOO-249.merge=refs/heads/feature/FOO-189-tests
```

This way, all the assumptions about a remote tracking branch being, well, a remote branch, fail 😅 Lemme safeguard the codebase against this case...

**Comment by PawelLipski** [comment]
Done on #601
