### ISSUE TITLE
Unhandled exception is thrown when forkpoint is overriden with invalid commit hash

### ISSUE THREAD

**Issue by MaciejG604** [PawelLipski/git-machete#648]
# Overview
Git machete throws unhandled exceptions if the the forkpoint overrided in the .git/config file is an invalid commit hash

Related: #609 

## Actual behavior/command output
```
mgajek$ git machete fork-point

Traceback (most recent call last):
  File "/opt/homebrew/bin/git-machete", line 20, in <module>
    cli.main()
  File "/opt/homebrew/Cellar/git-machete/3.12.0/libexec/lib/python3.10/site-packages/git_machete/cli.py", line 829, in main
    launch(sys.argv[1:])
  File "/opt/homebrew/Cellar/git-machete/3.12.0/libexec/lib/python3.10/site-packages/git_machete/cli.py", line 607, in launch
    print(machete_client.fork_point(
  File "/opt/homebrew/Cellar/git-machete/3.12.0/libexec/lib/python3.10/site-packages/git_machete/client.py", line 1207, in fork_point
    hash, containing_branch_pairs = self.__fork_point_and_containing_branch_pairs(
  File "/opt/homebrew/Cellar/git-machete/3.12.0/libexec/lib/python3.10/site-packages/git_machete/client.py", line 1151, in __fork_point_and_containing_branch_pairs
    overridden_fp_hash = self.__get_overridden_fork_point(branch)
  File "/opt/homebrew/Cellar/git-machete/3.12.0/libexec/lib/python3.10/site-packages/git_machete/client.py", line 1619, in __get_overridden_fork_point
    override_data: ForkPointOverrideData = self.__get_fork_point_override_data(branch)
  File "/opt/homebrew/Cellar/git-machete/3.12.0/libexec/lib/python3.10/site-packages/git_machete/client.py", line 1587, in __get_fork_point_override_data
    to = FullCommitHash.of(self.__git.get_config_attr_or_none(to_key) or "")
  File "/opt/homebrew/Cellar/git-machete/3.12.0/libexec/lib/python3.10/site-packages/git_machete/git_operations.py", line 122, in of
    raise TypeError(f'FullCommitHash requires length of 40. Given value: {value}, has length: {len(value)}.\n'
TypeError: FullCommitHash requires length of 40. Given value: lolxD, has length: 5.
Consider posting an issue on https://github.com/VirtusLab/git-machete/issues/new
```

## `git` and `git machete` versions

```
git --version
git version 2.37.0

git machete --version
git machete version 3.12.0
```

**Comment by PawelLipski** [comment]
See `git_machete.git_operations.RemoteBranchFullName.is_valid`, sth like that should probably be used for `git_machete.git_operations.FullCommitHash` as well
