### ISSUE TITLE
`advance` on an untracked branch crashes

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#837]
```
➜ (1) 16:57 ~/machete-sandbox <git:develop> $ git branch -Dr origin/develop
Deleted remote-tracking branch origin/develop (was b27a5d1).
➜ 16:57 ~/machete-sandbox <git:develop> $ g m s
Warn: since branch call-ws is no longer a descendant of commit aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, the fork point override to this commit no longer applies.
Consider running:
  git machete fork-point --unset-override call-ws

  develop (untracked)
  │
  └─allow-ownership-link  PR #123 (ahead of origin)
  │ │
  │ └─build-chain (untracked)
  │
  └─call-ws  PR #124 (ahead of origin)

  master
  │
  └─hotfix/add-trigger (diverged from origin)
➜ 16:57 ~/machete-sandbox <git:develop> $ g m advance
Warn: since branch call-ws is no longer a descendant of commit aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, the fork point override to this commit no longer applies.
Consider running:
  git machete fork-point --unset-override call-ws

Fast-forward develop to match call-ws? (y, N) y
Updating b27a5d1..5ec5066
Fast-forward
 call-ws-1st-round.txt | 0
 call-ws-2nd-round.txt | 0
 call-ws-Call-web.txt  | 0
 3 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 call-ws-1st-round.txt
 create mode 100644 call-ws-2nd-round.txt
 create mode 100644 call-ws-Call-web.txt

Branch develop is now fast-forwarded to match call-ws. Push develop to None? (y, N) y
Traceback (most recent call last):
  File "/Users/pawel_lipski/Library/Python/3.9/bin/git-machete", line 21, in <module>
    cli.main()
  File "/Users/pawel_lipski/Library/Python/3.9/lib/python/site-packages/git_machete/cli.py", line 865, in main
    launch(sys.argv[1:])
  File "/Users/pawel_lipski/Library/Python/3.9/lib/python/site-packages/git_machete/cli.py", line 570, in launch
    machete_client.advance(branch=current_branch, opt_yes=cli_opts.opt_yes)
  File "/Users/pawel_lipski/Library/Python/3.9/lib/python/site-packages/git_machete/client.py", line 641, in advance
    self.__git.push(remote, branch)
  File "/Users/pawel_lipski/Library/Python/3.9/lib/python/site-packages/git_machete/git_operations.py", line 414, in push
    self._run_git("push", "--set-upstream", *(opt_force + args))
  File "/Users/pawel_lipski/Library/Python/3.9/lib/python/site-packages/git_machete/git_operations.py", line 208, in _run_git
    exit_code = utils.run_cmd("git", git_cmd, *args, **kwargs_)
  File "/Users/pawel_lipski/Library/Python/3.9/lib/python/site-packages/git_machete/utils.py", line 122, in run_cmd
    flat_cmd: str = get_cmd_shell_repr(cmd, *args, env=kwargs.get('env'))
  File "/Users/pawel_lipski/Library/Python/3.9/lib/python/site-packages/git_machete/utils.py", line 196, in get_cmd_shell_repr
    return " ".join(env_repr + [cmd] + list(map(shell_escape, args)))
  File "/Users/pawel_lipski/Library/Python/3.9/lib/python/site-packages/git_machete/utils.py", line 187, in shell_escape
    return arg.replace("(", "\\(") \
AttributeError: 'NoneType' object has no attribute 'replace'
➜ (1) 16:57 ~/machete-sandbox <git:develop> $
```

**Comment by PawelLipski** [comment]
Discovered thanks to `strict_optional` in mypy (#118)
